1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Print the numpy version and the configuration

In [3]:
np.__version__

'1.19.5'

3. Create a null vector of size 10

In [10]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. How to find the memory size of any array

In [11]:
print("%d bytes" % (a.size * a.itemsize))

80 bytes


5. How to get the documentation of the numpy add function from the command line?

In [42]:
# %run `python -c "import numpy; numpy.info(numpy.add)"`

6. Create a null vector of size 10 but the fifth value which is 1

In [16]:
a[4] = 1 # a = null vector of size 10, fifth value = [4]
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

7. Create a vector with values ranging from 10 to 49

In [17]:
b = np.arange(10,50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

8. Reverse a vector (first element becomes last) 

In [18]:
b = b[::-1]
b

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

9. Create a 3x3 matrix with values ranging from 0 to 8

In [19]:
c = np.arange(9).reshape(3,3)
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [22]:
d = [1,2,0,0,4,0]
e = np.nonzero(d)
e

(array([0, 1, 4]),)

11. Create a 3x3 identity matrix

In [23]:
f = np.eye(3)
f

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12. Create a 3x3x3 array with random values

In [24]:
g = np.random.random((3,3,3))
g

array([[[0.57665648, 0.8579649 , 0.66351015],
        [0.2177089 , 0.39671749, 0.60792767],
        [0.64540189, 0.05778394, 0.98162071]],

       [[0.78664386, 0.10171485, 0.19709047],
        [0.77185267, 0.01486435, 0.44703444],
        [0.02524779, 0.47503746, 0.02073855]],

       [[0.32564981, 0.82811201, 0.00284343],
        [0.61978448, 0.54553271, 0.16167578],
        [0.78285187, 0.48270082, 0.22246369]]])

13. Create a 10x10 array with random values and find the minimum and maximum values

In [27]:
h = np.random.random((10,10))
hmin = h.min()
hmax = h.max()
print(h)
print("hmin = " + str(hmin))
print("hmax = " + str(hmax))

[[0.86830463 0.80761108 0.25406927 0.22878545 0.42988543 0.05013879
  0.29633292 0.8001682  0.88668405 0.48877495]
 [0.43833014 0.92381968 0.66338835 0.43280355 0.41892128 0.0716424
  0.7408408  0.30906246 0.51683052 0.07654236]
 [0.20979923 0.05906339 0.4586483  0.4760314  0.50907203 0.60946117
  0.85607403 0.88179515 0.08755175 0.1511445 ]
 [0.97386421 0.55722536 0.16987768 0.31648437 0.30849544 0.06021727
  0.38652297 0.79490324 0.4324706  0.61993865]
 [0.1402568  0.68694162 0.08391917 0.80445406 0.94638126 0.03200357
  0.78279823 0.66692721 0.48649138 0.54409941]
 [0.42289239 0.75688575 0.57555973 0.45679138 0.00260732 0.15806946
  0.15173745 0.3857949  0.47354022 0.31181322]
 [0.81620631 0.67391067 0.60826158 0.57576816 0.57501162 0.73163831
  0.63540366 0.08310859 0.56126584 0.72968729]
 [0.62481213 0.45342338 0.61564887 0.94508258 0.41757705 0.0640378
  0.772575   0.57695341 0.19643901 0.99786201]
 [0.77707609 0.59529107 0.06228876 0.48087171 0.91113319 0.63480682
  0.03695048 0

14. Create a random vector of size 30 and find the mean value

In [33]:
i = np.random.random(30)
imean = i.mean()
print(i)
print("i-mean = " + str(imean))

[0.11333636 0.18628037 0.06498508 0.06383617 0.63953416 0.22489633
 0.68269548 0.01448602 0.93425156 0.44400727 0.84583004 0.59382823
 0.78011324 0.36741457 0.88628196 0.66329275 0.64984425 0.74753757
 0.09707171 0.81718894 0.35009411 0.30997623 0.93906392 0.8702655
 0.52670864 0.15349176 0.20952127 0.82790643 0.11478259 0.50665941]
i-mean = 0.4875060629360688


15. Create a 2d array with 1 on the border and 0 inside

In [35]:
j = np.ones((5,5))
j[1:-1,1:-1] = 0
j

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

16. How to add a border (filled with 0's) around an existing array?

In [36]:
k = np.ones((5,5))
k_1 = np.pad(k, pad_width=1, mode='constant', constant_values=0)
k_1

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

What is the result of the following expression? <br>
0 * np.nan <br>
np.nan == np.nan <br>
np.inf > np.nan <br>
np.nan - np.nan <br>
np.nan in set([np.nan]) <br>
0.3 == 3 * 0.1 <br>

In [37]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [38]:
l = np.diag(1+np.arange(4),k=-1)
print(l)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [39]:
m = np.zeros((8,8),dtype=int)
m[1::2,::2] = 1
m[::2,1::2] = 1
print(m)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [40]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)
